server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  mongodb:
    uri: mongodb://test:test@127.0.0.1:27017/test

info:
  app:
    name: '@project.artifactId@'
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/, http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      my-metadata: Provides user metadata